### PR TITLE
Feature/main rendering

### PR DESCRIPTION
**Pull request by Minji1234**
Now It successfully works and renders when there is no question or answer.

### CODE REVIEW

**Comment by Minji1234** [comment]
Also you can successfully like or dislike answers on own profile.

**Comment by taehwoi** [comment]
> Also you can successfully like or dislike answers on own profile.

Wouldn't this kind of defeat the purpose of measuring user reliability?

**Comment by rachelg98** [comment]
Great job! Perhaps we can change the condition for disabling ratings in the backend to include, if the author is the currently logged in user. That way you can't rate your own answers but you can still rate answers in other users' profiles :)

**Review by rachelg98 — APPROVED** [review]
LGTM

**Pull request merged**
